package:
  name: brian2
  version: 2.0a7

source:
  fn: Brian2-2.0a7.tar.bz2
  url: https://pypi.python.org/packages/source/B/Brian2/Brian2-2.0a7.tar.bz2
  md5: 39a5c651cc0669e64be2d78748f5f208

requirements:
  build:
    - python
    - distribute
    - numpy
    - scipy
    - sympy
    - pyparsing
    - jinja2

  run:
    - python
    - distribute
    - numpy
    - scipy
    - sympy
    - pyparsing
    - jinja2

test:
  # Python imports
  imports:
    - brian2

  requires:    
    - nose

about:
  home: http://www.briansimulator.org/
  license: CeCILLv2.1

